services:
  db:
    image: pgvector/pgvector:0.8.1-pg16-trixie
    volumes:
      - ./docker/pgdata:/varlib/postgresql/data/pgdata
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: ragKnowledge
      POSTGRES_USER: ragKnowledge
      POSTGRES_PASSWORD: ragKnowledge1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ragKnowledge -U ragKnowledge"]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
